name: Dual Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu
          git clone https://github.com/mantesh20/practice.git app || (cd app && git pull origin main)
          
          # Stop existing containers
          docker stop cicd-container calculator-container || true
          docker rm cicd-container calculator-container || true
          
          # Build and run CICD container (Port 80)
          cd app/CICD
          docker build -f Dockerfile.cicd -t cicd-app .
          docker run -d --name cicd-container -p 80:80 cicd-app
          
          # Build and run Calculator container (Port 8080)
          cd ../code
          docker build -f Dockerfile.calculator -t calculator-app .
          docker run -d --name calculator-container -p 8080:80 calculator-app
          
          echo "Dual deployment completed successfully!"
          echo "Registration Form: http://$(curl -s ifconfig.me):80"
          echo "Calculator: http://$(curl -s ifconfig.me):8080"
